name: Test Parallel Crawlers

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        range:
          - { start: 1, end: 2 }
          - { start: 2, end: 3 }
          - { start: 3, end: 4 }
          - { start: 4, end: 5 }
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run partial crawler
        run: |
          python main.py \
          --start ${{ matrix.range.start }} \
          --end ${{ matrix.range.end }}
      - name: Upload partial results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.range.start }}-${{ matrix.range.end }}
          path: data/*.json
  merge-results:
    runs-on: ubuntu-latest
    needs: crawl
    steps:
      - uses: actions/checkout@v4
      - name: Delete old *.json
        run: |
          rm -r ./data/*.json

      - name: Download all partial results
        uses: actions/download-artifact@v4
        with:
          path: data/

      - name: Merge JSON results
        run: |
          ll
          ll ./data
      - name: Commit and push merged results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update merged crawler results" || echo "No changes to commit"
          git push
